// Сжатый опросник для пакетной генерации — минимум полей на весь период.
import type { QuestionnaireSchema } from "../api/types";

export const BATCH_QUESTIONNAIRE: QuestionnaireSchema = {
  document_type: "batch",
  version: 1,
  questions: [
    {
      id: "dynamics",
      label: "Динамика за период",
      type: "select",
      required: true,
      allow_custom: true,
      default: "no_change",
      group: "Состояние",
      options: [
        { value: "no_change", label: "без существенных изменений" },
        { value: "positive", label: "с положительной динамикой" },
        { value: "slight_improvement", label: "с незначительным улучшением" },
        { value: "worsening", label: "с ухудшением" },
        { value: "stable_positive", label: "со стойкой положительной динамикой" },
      ],
    },
    {
      id: "mood",
      label: "Фон настроения (тренд)",
      type: "select",
      required: true,
      allow_custom: true,
      default: "even",
      group: "Состояние",
      options: [
        { value: "even", label: "ровный" },
        { value: "lowered", label: "снижен" },
        { value: "unstable", label: "неустойчивый" },
        { value: "dysphoric", label: "с оттенком дисфории" },
      ],
    },
    {
      id: "behavior",
      label: "Поведение и режим",
      type: "select",
      required: true,
      allow_custom: true,
      default: "ordered",
      group: "Поведение",
      options: [
        { value: "ordered", label: "упорядочен, режим соблюдает" },
        { value: "minor_remarks", label: "режим на негрубых замечаниях" },
        { value: "violates", label: "нарушает режим" },
        { value: "restless", label: "двигательно беспокоен" },
      ],
    },
    {
      id: "sleep",
      label: "Сон (тренд)",
      type: "select",
      required: true,
      allow_custom: true,
      default: "not_disturbed",
      group: "Сон и аппетит",
      options: [
        { value: "not_disturbed", label: "не нарушен" },
        { value: "hard_to_fall_asleep", label: "трудности засыпания" },
        { value: "superficial", label: "поверхностный" },
        { value: "sufficient", label: "достаточен" },
      ],
    },
    {
      id: "appetite",
      label: "Аппетит / питание",
      type: "select",
      required: true,
      allow_custom: true,
      default: "preserved",
      group: "Сон и аппетит",
      options: [
        { value: "preserved", label: "сохранён" },
        { value: "decreased", label: "снижен" },
        { value: "selective", label: "избирательный" },
        { value: "increased", label: "повышен" },
      ],
    },
    {
      id: "feeding_weight",
      label: "Динамика веса / кормления",
      type: "text",
      required: false,
      allow_custom: true,
      group: "Сон и аппетит",
      help: "Кратко: прибавка веса, режим кормления (без персональных данных).",
    },
    {
      id: "tolerance",
      label: "Переносимость терапии",
      type: "select",
      required: true,
      allow_custom: true,
      default: "good",
      group: "Терапия",
      options: [
        { value: "good", label: "переносит хорошо" },
        { value: "satisfactory", label: "удовлетворительно" },
        { value: "adverse", label: "есть нежелательные явления" },
        { value: "none", label: "терапию не получает" },
      ],
    },
    {
      id: "complaints",
      label: "Жалобы",
      type: "select",
      required: true,
      allow_custom: true,
      default: "none",
      group: "Терапия",
      options: [
        { value: "none", label: "не предъявляет" },
        { value: "cannot_formulate", label: "самостоятельно не формирует" },
        { value: "present", label: "есть жалобы" },
      ],
    },
    {
      id: "key_events",
      label: "Ключевые события периода",
      type: "text",
      required: false,
      allow_custom: true,
      group: "События",
      help: "Консультации, процедуры, эпизоды поведения (без персональных данных).",
    },
    {
      id: "period_dynamics",
      label: "Динамика для осмотра 10 дней",
      type: "select",
      required: false,
      allow_custom: true,
      default: "improvement",
      group: "Осмотр 10 дней",
      help: "Используется в дни 10, 20, 30… для этапного эпикриза.",
      options: [
        { value: "improvement", label: "с улучшением в условиях отделения" },
        { value: "slight_improvement", label: "с незначительным улучшением" },
        { value: "no_improvement", label: "без заметного улучшения" },
        { value: "no_change", label: "без существенных изменений" },
      ],
    },
    {
      id: "syndrome",
      label: "Синдром (для осмотра 10 дней)",
      type: "select",
      required: false,
      allow_custom: true,
      default: "anxiety_depressive",
      group: "Осмотр 10 дней",
      options: [
        { value: "anxiety_depressive", label: "тревожно-депрессивный" },
        { value: "psychopathic", label: "психопатоподобный" },
        { value: "emotional_volitional", label: "эмоционально-волевой неустойчивости" },
        { value: "anxious", label: "тревожный" },
        { value: "asthenic", label: "астенический" },
      ],
    },
  ],
};
